### ISSUE TITLE
Will this work on macOS?

### ISSUE THREAD

**Issue by enzyme69** [Snowdaw/blender-python-geometry-node#1]
I have not tested it, but is this node addon for GN possibly work for macOS?

**Comment by Snowdaw** [comment]
Because the geometry node system isn't exposed to the Python API in normal Blender I had to fork Blender to implement this in the C++ codebase. As a result this is a different build of Blender and not an addon like you may be used to. It should compile fine on macos but I haven't tested it yet myself.

I am working on an update at the moment and will try to include an arm64 mac build when it's ready.

**Comment by Snowdaw** [comment]
The update is out and an arm64 mac build is in the release.
